#!/usr/bin/env bash
git mv src/tests/stdlib/confirm.output.txt src/tests/stdlib/env_input_confirm.output.txt
git mv src/tests/stdlib/glob_absolute_missing_file.ab src/tests/stdlib/fs_glob_absolute_missing_file.ab
git mv src/tests/stdlib/glob_absolute_multiple_globs.ab src/tests/stdlib/fs_glob_absolute_multiple_globs.ab
git mv src/tests/stdlib/glob_absolute_wild_char.ab src/tests/stdlib/fs_glob_absolute_wild_char.ab
git mv src/tests/stdlib/glob_absolute_wild_star.ab src/tests/stdlib/fs_glob_absolute_wild_star.ab
git mv src/tests/stdlib/glob_absolute_with_spaces.ab src/tests/stdlib/fs_glob_absolute_with_spaces.ab
git mv src/tests/stdlib/glob_injection_attack.ab src/tests/stdlib/fs_glob_injection_attack.ab
git mv src/tests/stdlib/glob_relative_missing_file.ab src/tests/stdlib/fs_glob_relative_missing_file.ab
git mv src/tests/stdlib/glob_relative_multiple_globs.ab src/tests/stdlib/fs_glob_relative_multiple_globs.ab
git mv src/tests/stdlib/glob_relative_wild_char.ab src/tests/stdlib/fs_glob_relative_wild_char.ab
git mv src/tests/stdlib/glob_relative_wild_star.ab src/tests/stdlib/fs_glob_relative_wild_star.ab
git mv src/tests/stdlib/glob_relative_with_spaces.ab src/tests/stdlib/fs_glob_relative_with_spaces.ab
git mv src/tests/stdlib/includes_empty_num_array.ab src/tests/stdlib/array_contains_empty_num_array.ab
git mv src/tests/stdlib/includes_empty_text_array.ab src/tests/stdlib/array_contains_empty_text_array.ab
git mv src/tests/stdlib/includes_exact_match.ab src/tests/stdlib/array_contains_exact_match.ab
git mv src/tests/stdlib/includes_partial_match_with_expanded_element.ab src/tests/stdlib/array_contains_partial_match_with_expanded_element.ab
git mv src/tests/stdlib/includes_prefix_match.ab src/tests/stdlib/array_contains_prefix_match.ab
git mv src/tests/stdlib/includes_text_array.ab src/tests/stdlib/array_contains_text_array.ab
git mv src/tests/stdlib/replace_regex_basic.ab src/tests/stdlib/text_replace_regex_basic.ab
git mv src/tests/stdlib/replace_regex_ext.ab src/tests/stdlib/text_replace_regex_ext.ab
git mv src/tests/stdlib/split_multiline.ab src/tests/stdlib/text_split_multiline.ab
git mv src/tests/stdlib/trim.output.txt src/tests/stdlib/text_trim.output.txt
git mv src/tests/stdlib/trim_left.output.txt src/tests/stdlib/text_trim_left.output.txt
git mv src/tests/stdlib/trim_right.output.txt src/tests/stdlib/text_trim_right.output.txt
